"""Add allow_login and allow_create

Revision ID: e2c7ad4b34a3
Revises: 54b4a21149ef
Create Date: 2025-03-04 21:49:15.930501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2c7ad4b34a3'
down_revision = '54b4a21149ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clipboard', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_create', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allow_login')
        batch_op.drop_column('allow_create')

    with op.batch_alter_table('clipboard', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
